// Code generated by MockGen. DO NOT EDIT.
// Source: internal/contracts/expense/repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	contracts "github.com/Ahhasha/Tracker-bot/internal/contracts"
	model "github.com/Ahhasha/Tracker-bot/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockExpenseRepository is a mock of ExpenseRepository interface.
type MockExpenseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExpenseRepositoryMockRecorder
}

// MockExpenseRepositoryMockRecorder is the mock recorder for MockExpenseRepository.
type MockExpenseRepositoryMockRecorder struct {
	mock *MockExpenseRepository
}

// NewMockExpenseRepository creates a new mock instance.
func NewMockExpenseRepository(ctrl *gomock.Controller) *MockExpenseRepository {
	mock := &MockExpenseRepository{ctrl: ctrl}
	mock.recorder = &MockExpenseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExpenseRepository) EXPECT() *MockExpenseRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockExpenseRepository) Create(ctx context.Context, db contracts.DBTX, expense model.Expense) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, db, expense)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockExpenseRepositoryMockRecorder) Create(ctx, db, expense interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExpenseRepository)(nil).Create), ctx, db, expense)
}

// GetPeriodWithCategory mocks base method.
func (m *MockExpenseRepository) GetPeriodWithCategory(ctx context.Context, db contracts.DBTX, userID int64, start, end time.Time) ([]model.ExpenseWithCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeriodWithCategory", ctx, db, userID, start, end)
	ret0, _ := ret[0].([]model.ExpenseWithCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeriodWithCategory indicates an expected call of GetPeriodWithCategory.
func (mr *MockExpenseRepositoryMockRecorder) GetPeriodWithCategory(ctx, db, userID, start, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeriodWithCategory", reflect.TypeOf((*MockExpenseRepository)(nil).GetPeriodWithCategory), ctx, db, userID, start, end)
}

// MockCategoryRepository is a mock of CategoryRepository interface.
type MockCategoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryRepositoryMockRecorder
}

// MockCategoryRepositoryMockRecorder is the mock recorder for MockCategoryRepository.
type MockCategoryRepositoryMockRecorder struct {
	mock *MockCategoryRepository
}

// NewMockCategoryRepository creates a new mock instance.
func NewMockCategoryRepository(ctrl *gomock.Controller) *MockCategoryRepository {
	mock := &MockCategoryRepository{ctrl: ctrl}
	mock.recorder = &MockCategoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryRepository) EXPECT() *MockCategoryRepositoryMockRecorder {
	return m.recorder
}

// GetByName mocks base method.
func (m *MockCategoryRepository) GetByName(ctx context.Context, db contracts.DBTX, userID int64, name string) (model.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, db, userID, name)
	ret0, _ := ret[0].(model.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockCategoryRepositoryMockRecorder) GetByName(ctx, db, userID, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockCategoryRepository)(nil).GetByName), ctx, db, userID, name)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetIDByTgID mocks base method.
func (m *MockUserRepository) GetIDByTgID(ctx context.Context, db contracts.DBTX, tgUserID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDByTgID", ctx, db, tgUserID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDByTgID indicates an expected call of GetIDByTgID.
func (mr *MockUserRepositoryMockRecorder) GetIDByTgID(ctx, db, tgUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDByTgID", reflect.TypeOf((*MockUserRepository)(nil).GetIDByTgID), ctx, db, tgUserID)
}
