// Code generated by MockGen. DO NOT EDIT.
// Source: internal/contracts/expense/service.go

// Package mock_expense is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	expense "github.com/Ahhasha/Tracker-bot/internal/contracts/expense"
	model "github.com/Ahhasha/Tracker-bot/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddExpense mocks base method.
func (m *MockService) AddExpense(ctx context.Context, userID int64, req expense.ExpenseRequest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddExpense", ctx, userID, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddExpense indicates an expected call of AddExpense.
func (mr *MockServiceMockRecorder) AddExpense(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddExpense", reflect.TypeOf((*MockService)(nil).AddExpense), ctx, userID, req)
}

// Month mocks base method.
func (m *MockService) Month(ctx context.Context, tgUserID int64) (model.PeriodReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Month", ctx, tgUserID)
	ret0, _ := ret[0].(model.PeriodReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Month indicates an expected call of Month.
func (mr *MockServiceMockRecorder) Month(ctx, tgUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Month", reflect.TypeOf((*MockService)(nil).Month), ctx, tgUserID)
}

// Today mocks base method.
func (m *MockService) Today(ctx context.Context, tgUserID int64) (model.PeriodReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Today", ctx, tgUserID)
	ret0, _ := ret[0].(model.PeriodReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Today indicates an expected call of Today.
func (mr *MockServiceMockRecorder) Today(ctx, tgUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Today", reflect.TypeOf((*MockService)(nil).Today), ctx, tgUserID)
}

// Week mocks base method.
func (m *MockService) Week(ctx context.Context, tgUserID int64) (model.PeriodReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Week", ctx, tgUserID)
	ret0, _ := ret[0].(model.PeriodReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Week indicates an expected call of Week.
func (mr *MockServiceMockRecorder) Week(ctx, tgUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Week", reflect.TypeOf((*MockService)(nil).Week), ctx, tgUserID)
}
